### ISSUE TITLE
CMakeLists.txt file is not required to be edited (in README)

### ISSUE THREAD

**Issue by ProjectHSI** [nicvagn/NicLink#8]
Look into the -D flag in CMake for further information. The -D flag allows you to specify variables in CMake (at configuration-time).

I would try and submit a PR but I'm not sure of the exact requirements for each options. Alternatively you could try and auto-detect for a specific system.

**Comment by ProjectHSI** [comment]
https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-D

**Comment by nicvagn** [comment]
thank you.

I appreciate the help. 

I learned cmake ((( badly ))) for this project.

I may look into it, but honestly I built this because I wanted it. 

I want to share it, but making it a commodity is not fun, and  I did this for fun, you know?

**Comment by ProjectHSI** [comment]
ok. understandable.

**Comment by nicvagn** [comment]
I really appreciate the suggestion, and will look into it! 

I do want people to use it, and I do want to find ways to make it easier for people to install.

But, it is an area I have no knowledge of.

The public relations part of making useful software people actually use, is not my jam.

As I made a release, it is now time to make it usable for the general peer.

I only have GNU/Linux on my machine, and I am not willing to buy windows just to make my program run on it.

**Comment by ProjectHSI** [comment]
if it's ok i could try and create documentation using the -D flag, can you rewrite the setting up for your machine section in the README? i can't understand the dependencies for each of the options there or what should be set.

**Comment by nicvagn** [comment]
> if it's ok i could try and create documentation using the -D flag, can you rewrite the setting up for your machine section in the README? i can't understand the dependencies for each of the options there or what should be set.

I will, I am sorry for the difficulty

**Comment by nicvagn** [comment]
TODO: set for your system:
    NOTE: removed as not debbuging c++ code link_libraries(spdlog_header_only)
    set(SPDLOG OFF) # Very fast, header-only/compiled, C++ logging library.
    NOTE: not needed if using hidraw backend to libusb
    set(LIBUSB OFF) # i am using th hidraw backend adjust if you are not ant need libusb
    see https://github.com/libusb/libusb
    see thirdparty/hidapi/README.md
    option(HIDAPI_WITH_LIBUSB "Build LIBUSB-based implementation of HIDAPI" ON)
    option(HIDAPI_WITH_LIBUSB "Build LIBUSB-based implementation of HIDAPI" OFF)****


Spdlog - legacy option from the chessnut EasyLink SDK. I have never used.

LibUSB - needed to use LibUSB backend. This will be needed for ALL non Linux OS's, as hidhaw is a Linux kernel way to interact with human interface devices.

So this should be pressed for most us cases.

So hidraw should be not selected,
option(HIDAPI_WITH_LIBUSB "Build LIBUSB-based implementation of HIDAPI" ON)

And the LibUSB backend should be used.

Honestly, I don't remember much more information about this.

I have terrible memory from a head injury, and I don't remember much about the cmake file... I have not changed it much since I finished professional cmake...

**Comment by nicvagn** [comment]
I will try and edit the main file when I get home. Away for Father's day

**Comment by nicvagn** [comment]
I have edited the CMakeLiests.txt to use LibUsb. Lib USB is cross platform :. It should no longer be required to edit the CMakeLists.txt.

Thank you for helping me address this.

I do not think editing the CMakeList.txt is needed anymore

**Comment by nicvagn** [comment]
I ended up simplifying the file and using the libusb back end by default :. It should not be required to edit the file. 

LibUSB cover's all major operating systems.

The usb backend was the only thing (I think) that had to be configured.

**Comment by ProjectHSI** [comment]
remember to close issues after you're done with them.

**Comment by nicvagn** [comment]
Thank you for the help. I am new to working sudo publicly on github
